### ISSUE TITLE
TWCManager crashes overnight with 'yesterday' is not defined

### ISSUE THREAD

**Issue by JinbaIttai** [ngardiner/TWCManager#144]
I woke up this morning to find TWCManager had crashed and was looping the following message continuously:

```
Traceback (most recent call last):
  File "/home/pi/TWCManager/TWCManager.py", line 876, in <module>
    slaveTWC.receive_slave_heartbeat(heartbeatData)
  File "/home/pi/TWCManager/lib/TWCManager/TWCSlave.py", line 553, in receive_slave_heartbeat
    self.master.getModuleByName("Policy").setChargingPerPolicy()
  File "/home/pi/TWCManager/lib/TWCManager/Policy/Policy.py", line 154, in setChargingPerPolicy
policy["match"], policy["condition"], policy["value"]
  File "/home/pi/TWCManager/lib/TWCManager/Policy/Policy.py", line 345, in checkConditions
    if self.doesConditionMatch(match, condition, value, exitOn) == exitOn:
  File "/home/pi/TWCManager/lib/TWCManager/Policy/Policy.py", line 306, in doesConditionMatch
    match = self.policyValue(match)
  File "/home/pi/TWCManager/lib/TWCManager/Policy/Policy.py", line 269, in policyValue
    return self.master.checkScheduledCharging()
  File "/home/pi/TWCManager/lib/TWCManager/TWCMaster.py", line 127, in checkScheduledCharging
    and (self.getScheduledAmpsDaysBitmap() & (1 << yesterday))
NameError: name 'yesterday' is not defined

```

In [this commit on Nov 3 2019](https://github.com/ngardiner/TWCManager/commit/80bdfa925c9999167950079ddf2d4ed3b8a889c0#diff-51d7f0d409ca0161ae88ed5d189155ed) some code was moved from `TWCSlave.py` to  `TWCMaster.py` which includes the bit that handles "a time like 8am to 7am which we must interpret as the 23-hour period after 8am or before 7am" but misses the bit where `yesterday` is defined - causing the crash when it reaches this code:

```python
                if (
                    hourNow >= self.settings.get("scheduledAmpsStartHour", -1)
                    and (self.getScheduledAmpsDaysBitmap() & (1 << ltNow.tm_wday))
                ) or (
                    hourNow < self.getScheduledAmpsEndHour()
                    and (self.getScheduledAmpsDaysBitmap() & (1 << yesterday))
                ):  
```

```diff
diff -r -u TWCManager-1.2.0/lib/TWCManager/TWCMaster.py TWCManager/lib/TWCManager/TWCMaster.py
--- TWCManager-1.2.0/lib/TWCManager/TWCMaster.py        2020-08-05 13:25:15.989067466 +0800
+++ TWCManager/lib/TWCManager/TWCMaster.py      2020-08-05 14:08:44.105960233 +0800
@@ -119,6 +119,10 @@
                 # 7am, we apply scheduledAmpsMax from Monday at 8am to Monday at
                 # 11:59pm, and on Tuesday at 12am to Tuesday at 6:59am.
                 hourNow = ltNow.tm_hour + (ltNow.tm_min / 60)
+                yesterday = ltNow.tm_wday - 1
+                if yesterday < 0:
+                    yesterday += 7
+                
                 if (
                     hourNow >= self.settings.get("scheduledAmpsStartHour", -1)
                     and (self.getScheduledAmpsDaysBitmap() & (1 << ltNow.tm_wday))
```

**Comment by MikeBishop** [comment]
I'm happy to take both of these changes as PRs, or just make the commit for you.
