### ISSUE TITLE
TWC has no connection to master (red light blinking) but TWCM is up & running 

### ISSUE THREAD

**Issue by danielsan1** [ngardiner/TWCManager#365]
Hi @ngardiner I'm experiencing a strange issue running v 1.2.2 (everything worked fine over the last 3 months):
I tried the stop charging option "stop responding to slaves" for the fist time, as my neighbor charged his M3 for the first time on my TWC. It worked fine and charging stoped as the sun went down. But now the TWC is blinking red (error code says "no master") and I tried everything to get it back to normal. I changed the stop charging method back to Tesla API, I restarted my RapsberryPi, the TWC - everything. But the TWC keeps blinking red and interestingly TWCM is not showing the usual data like "Chargepoint" information (everything is 0) or the Solar Surplus or actual consumption of the house what it usually does. 

Any idea what I can do? I didn't change anything except the stop charging option in the dropdown menu...

Thank you very much in advance!

**Comment by danielsan1** [comment]
I got it fixed by upgrading to 1.2.3! 

Before that I saw this error via SSH:

`16:36:20 TWCManager 20 Unhandled Exception:Traceback (most recent call last):
Aug 28 16:36:20 twcmanager python3[933]:   File "/home/pi/TWCManager/TWCManager.py", line 602, in <module>
Aug 28 16:36:20 twcmanager python3[933]:     slaveTWC.send_master_heartbeat()
Aug 28 16:36:20 twcmanager python3[933]:   File "/home/pi/TWCManager/lib/TWCManager/TWCSlave.py", line 334, in send_master_heartbeat
Aug 28 16:36:20 twcmanager python3[933]:     if self.master.settings.get("respondToSlavesExpiry", time.time()) > time.time():
Aug 28 16:36:20 twcmanager python3[933]: NameError: name 'time' is not defined`

Not really sure what it means but overall I'm pretty sure that TWCM got stuck in the "stop responding to slave" mode. Also the blinking code from the TWC was related to a master/slave issue according to the manual. So TWCM stoped responding to the slave and never started again (even I was changing the settings a 100 times, rebooting, restarting etc.)
