### ISSUE TITLE
Parser error in config.json after fresh install?

### ISSUE THREAD

**Issue by calleman** [ngardiner/TWCManager#444]
Hi all,

First - I have probably forgotten something trivial.. I have been running the 1.2.3 code successfully as a service for 5 months on a RPi Zero. The loadbalancing stopped working so I decided to upgrade. I tried the regular update via pip first but ran in to problems. I decided to delete the TWCManager completly and did a new git clone and a checkout on v1.2.6. All Fine. I tried to start manually without tamper with the /etc/twcmanager/config.json but ran in to parser errors. I then tried to start with the original config.json and TWCManager started without any problems. Happy with that I edited the config.json with my values and the same parser errors came up again..

I have added the TWCManager user, did the chown etc.

If I edit the config.json back to the original the parser error dissapear for every edit back to the original file.

Sample of the traceback right now as I am down to the HASS config in the file when starting manually with "sudo -u twcmanager python -m TWCManager":

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/TWCManager/TWCManager.py", line 34, in <module>
    import TWCManager.TWCManager
  File "/home/pi/TWCManager/lib/TWCManager/TWCManager.py", line 137, in <module>
    config = yaml.safe_load(configtext)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 549, in parse_flow_mapping_key
    raise ParserError("while parsing a flow mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 494, column 17:
            "HASS": {
                    ^
expected ',' or '}', but got ':'
  in "<unicode string>", line 499, column 23:
                "serverIP": "192.168.0.1.1",
 

What have I missed?

Thanks for the great support!

**Comment by calleman** [comment]
Hi again,

After a bit of tinkering I found the problem. I have a password under logging/sql that consists of 2 special characters - They need to be in HEX UTF32 format - or at least that worked. That wasnt required before the upgrade to 1.2.6?

Old:
"password": "#password!"

New:
"password": "\u0023password\u0021"


Thanks all, closing this..
