### ISSUE TITLE
HTTP access

### ISSUE THREAD

**Issue by Samiam789** [ngardiner/TWCManager#529]
I'm using version 1.3.0 on a pi zero running bullseye lite.

When I try and access the http page on my home network I get a blank page and the error below.

I'm very new to raspberry pi so it may well be something I've done!

Jul 26 14:13:48 twcmanagerpi python3[337]: 14:13:48 ⛽ Manager  20 Charge when above 12A (minAmpsPerTWC).
Jul 26 14:13:51 twcmanagerpi python3[337]: ----------------------------------------
Jul 26 14:13:51 twcmanagerpi python3[337]: Exception occurred during processing of request from ('[10.0.0.12](http://10.0.0.12/)', [47784](tel:47784))
Jul 26 14:13:51 twcmanagerpi python3[337]: Traceback (most recent call last):
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/lib/python3.9/[socketserver.py](http://socketserver.py/)", line 650, in process_request_thread
Jul 26 14:13:51 twcmanagerpi python3[337]:     self.finish_request(request, client_address)
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/lib/python3.9/[socketserver.py](http://socketserver.py/)", line 360, in finish_request
Jul 26 14:13:51 twcmanagerpi python3[337]:     self.RequestHandlerClass(request, client_address, self)
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/TWCManager/Control/[HTTPControl.py](http://httpcontrol.py/)", line 158, in __init__
Jul 26 14:13:51 twcmanagerpi python3[337]:     BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/lib/python3.9/[socketserver.py](http://socketserver.py/)", line 720, in __init__
Jul 26 14:13:51 twcmanagerpi python3[337]:     self.handle()
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/lib/python3.9/http/[server.py](http://server.py/)", line 427, in handle
Jul 26 14:13:51 twcmanagerpi python3[337]:     self.handle_one_request()Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/lib/python3.9/http/[server.py](http://server.py/)", line 415, in handle_one_request
Jul 26 14:13:51 twcmanagerpi python3[337]:     method()
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/TWCManager/Control/[HTTPControl.py](http://httpcontrol.py/)", line 777, in do_GET
Jul 26 14:13:51 twcmanagerpi python3[337]:     page = self.template.render(vars(self))
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](http://environment.py/)", line 1301, in render
Jul 26 14:13:51 twcmanagerpi python3[337]:     self.environment.handle_exception()
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](http://environment.py/)", line 936, in handle_exception
Jul 26 14:13:51 twcmanagerpi python3[337]:     raise rewrite_traceback_stack(source=source)
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/TWCManager/Control/themes/Modern/main.html.j2", line 1, in top-level template code
Jul 26 14:13:51 twcmanagerpi python3[337]:     {% extends "master.html.j2" %}
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/TWCManager/Control/themes/Modern/master.html.j2", line 11, in top-level template code
Jul 26 14:13:51 twcmanagerpi python3[337]:     {% block content %}{% endblock %}
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/TWCManager/Control/themes/Modern/main.html.j2", line 306, in block 'content'
Jul 26 14:13:51 twcmanagerpi python3[337]:     <label for="chargeNowRate" class="form-label text-muted">Charge with <span class="text-dark font-weight-bold" id="{{ twcid }}_ampsVal">{{ ampsMin[0] }}</span> A</label>
Jul 26 14:13:51 twcmanagerpi python3[337]:   File "/usr/local/lib/python3.9/dist-packages/jinja2/[environment.py](http://environment.py/)", line 466, in getitem
Jul 26 14:13:51 twcmanagerpi python3[337]:     return obj[argument]
Jul 26 14:13:51 twcmanagerpi python3[337]: jinja2.exceptions.UndefinedError: list object has no element 1
Jul 26 14:13:51 twcmanagerpi python3[337]: ----------------------------------------

**Comment by Samiam789** [comment]
All working now. I think there was a problem with the way I'd set up the HASS module for polling my solar data.
