### ISSUE TITLE
MySQL logging

### ISSUE THREAD

**Issue by ghost** [ngardiner/TWCManager#579]
Hello.

I just ran into this error using the MySQL logging module.
The tables are set to values, taht are provided in the docu.

```
twcmanager_1  | Traceback (most recent call last):
twcmanager_1  |   File "/usr/src/TWCManager/lib/TWCManager/Control/HTTPControl.py", line 1351, in process_graphs
twcmanager_1  |     result = module.queryGreenEnergy(
twcmanager_1  |   File "/usr/src/TWCManager/lib/TWCManager/Logging/MySQLLogging.py", line 255, in queryGreenEnergy
twcmanager_1  |     self.db.ping(reconnect=True)
twcmanager_1  | AttributeError: 'NoneType' object has no attribute 'ping'
```

Can this cause any issues, or is this safe to ignore?

Thanks.

**Comment by MikeBishop** [comment]
That suggests that the `db` object is null, which probably means nothing is getting logged. I don't use the MySQL logger myself, but it's plainly not safe to ignore if you need that logging method.
